begin;
do $$ declare u uuid:=gen_random_uuid();other_user uuid:=gen_random_uuid();client uuid:=gen_random_uuid();eid uuid:=gen_random_uuid();r uuid;c uuid;items jsonb:='[]';batch jsonb;code text;sid uuid;sid2 uuid;sid3 uuid;op uuid;payload jsonb;receipt jsonb;before_count integer;
begin
 insert into auth.users(id) values(u),(other_user);insert into public.outreach_app_access(user_id) values(u),(other_user);
 perform set_config('request.jwt.claim.sub',u::text,true);
 insert into public.outreach_runs(run_date,generated_at_sgt) values(current_date,now()) returning id into r;
 for n in 1..3 loop
 insert into public.outreach_contacts(full_name,employer,linkedin_profile_url,first_recommended_date,last_recommended_date) values('Work fixture '||n,'Fixture','https://www.linkedin.com/in/work-fixture-'||n,current_date,current_date) returning id into c;
 insert into public.outreach_recommendations(run_id,contact_id,track,priority,fit_assessment,personalized_message,message_character_count,verified_at) values(r,c,'hiring_manager',n,'Fixture','Hello fixture',13,now());items:=items||jsonb_build_array(outreach_private.manual_invitation(c));end loop;
 batch:=public.manual_outreach('queue',jsonb_build_object('items',items,'request_id',gen_random_uuid()));code:=batch->>'batch_code';
 batch:=public.work_recording('inspect',jsonb_build_object('batch_code',code));sid:=(batch->'sessions'->0->>'session_id')::uuid;sid2:=(batch->'sessions'->1->>'session_id')::uuid;sid3:=(batch->'sessions'->2->>'session_id')::uuid;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform public.work_recording('inspect',jsonb_build_object('batch_code',code));raise exception 'FAIL anonymous';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',other_user::text,true);
 begin perform public.work_recording('inspect',jsonb_build_object('batch_code',code));raise exception 'FAIL wrong owner';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub',u::text,true);
 perform public.work_recording('allow_client',jsonb_build_object('client_id',client));
 perform set_config('request.jwt.claims',jsonb_build_object('sub',u,'client_id',client)::text,true);
 begin perform public.work_recording('begin',jsonb_build_object('session_id',sid,'execution_id',eid,'operation_id',gen_random_uuid()));raise exception 'FAIL unclaimed';exception when others then if sqlerrm='FAIL unclaimed' then raise;end if;end;
 perform public.work_recording('claim',jsonb_build_object('batch_code',code,'execution_id',eid,'operation_id',gen_random_uuid()));
 begin perform public.work_recording('claim',jsonb_build_object('batch_code',code,'execution_id',gen_random_uuid(),'operation_id',gen_random_uuid()));raise exception 'FAIL concurrent runner';exception when others then if sqlerrm='FAIL concurrent runner' then raise;end if;end;
 op:=gen_random_uuid();payload:=jsonb_build_object('session_id',sid,'execution_id',eid,'operation_id',op);
 receipt:=public.work_recording('begin',payload);if receipt<>public.work_recording('begin',payload) then raise exception 'Begin not idempotent';end if;
 begin perform public.work_recording('begin',jsonb_build_object('session_id',sid2,'execution_id',eid,'operation_id',gen_random_uuid()));raise exception 'FAIL pending attempt';exception when others then if sqlerrm='FAIL pending attempt' then raise;end if;end;
 op:=gen_random_uuid();payload:=jsonb_build_object('session_id',sid,'execution_id',eid,'operation_id',op,'outcome','sent','evidence','Visible Pending after sending exact frozen message','observed_at',now(),'confirmation_signal','linkedin_invitation_sent_visible');
 receipt:=public.work_recording('record',payload);if receipt<>public.work_recording('record',payload) or receipt<>public.work_recording('receipt',jsonb_build_object('operation_id',op)) then raise exception 'Recording not idempotent';end if;
 begin perform public.work_recording('record',payload||'{"outcome":"email_required"}');raise exception 'FAIL conflicting receipt';exception when others then if sqlerrm='FAIL conflicting receipt' then raise;end if;end;
 if (select count(*) from public.outreach_activities where contact_id=(items->0->>'contact_id')::uuid and activity_type='request_sent')<>1 then raise exception 'Duplicate activity';end if;
 perform public.work_recording('begin',jsonb_build_object('session_id',sid2,'execution_id',eid,'operation_id',gen_random_uuid()));
 perform public.work_recording('record',jsonb_build_object('session_id',sid2,'execution_id',eid,'operation_id',gen_random_uuid(),'outcome','uncertain','evidence','Browser interrupted before outcome could be established','observed_at',now()));
 if not exists(select 1 from outreach_private.work_recovery where session_id=sid2 and resolved_at is null) then raise exception 'Uncertain result lost recovery hold';end if;
 begin perform public.work_recording('begin',jsonb_build_object('session_id',sid3,'execution_id',eid,'operation_id',gen_random_uuid()));raise exception 'FAIL uncertain blocks next send';exception when others then if sqlerrm='FAIL uncertain blocks next send' then raise;end if;end;
 perform public.work_recording('recover',jsonb_build_object('session_id',sid2,'operation_id',gen_random_uuid(),'outcome','connect_unavailable','evidence','More menu checked; Connect unavailable, not a connection','observed_at',now()));
 insert into outreach_private.work_recovery(session_id,owner_id,reason) values(sid3,u,'Recovery fixture');
 perform public.work_recording('recover',jsonb_build_object('session_id',sid3,'operation_id',gen_random_uuid(),'outcome','email_required','evidence','Connect flow explicitly asks for email; no invitation sent','observed_at',now()));
 if (select connection_status from public.outreach_contacts where id=(items->2->>'contact_id')::uuid)<>'not_contacted' then raise exception 'Skip became connected';end if;
 if jsonb_array_length(outreach_private.rolling_queue_state()->'queues')<>0 then raise exception 'Completed queue retains slot';end if;
 update outreach_private.work_clients set enabled=false where owner_id=u;
 begin perform public.work_recording('inspect',jsonb_build_object('batch_code',code));raise exception 'FAIL revoked';exception when insufficient_privilege then null;end;
end $$;
rollback;
